# (PART) GitHub and Other Remote Hosts {-}

# Git $\ne$ GitHub

Thus far, everything is within your local computer and done using `git`. That is the **version control** portion of git, which is important and powerful. However, what makes git a efficient tool for collaboration is its power to share through remote hosts like **GitHub**.

* GitHub is not the only option, there are other companies that offer free remote hosting, here are a few alterantives [Bitbucket](https://bitbucket.org/), [Gitlab](https://gitlab.com/)

## Git is a remote server that hosts a repository (remote host)

Remember `git init` makes a `.git/` folder in your project. That is a local repository (local=lives on your computer).

GitHub is essentially a remote server that hosts a `.git/` folder. 
GitHub also comes with tons of tools to help you visualize and manage your repository.

## Create aa repository in on github (a remote repo)

* Navigate to https://github.com/your_username
	+ Click **Repositories** tab
	+ Click **New**
	+ Enter workdir as the Repository name, click **Create repository**

---
**You now have an empty remote repository and some instructions to populate it!**