# (PART) GitHub and Other Remote Hosts {-}
Thus far everything is within your local computer and done using `git`. That is the **version control** portion of git. Which is important and powerful. But what makes git a very strong tool for collaboration is sharing through remote hosts like Github (or other remote hosts).

* Github is not the only option, there are other companies that offer free remote hosting, here are a few alterantives [Bitbucket](https://bitbucket.org/), [Gitlab](https://gitlab.com/)


# Storing codes on Github

Remeber `git init` makes a `.git/` folder in your project, which is your local repository? Github is essentially a remote server that hosts a `.git/` folder. Github also comes with tons of tools to help you visualize and manage your repository.

## Create a remote repository 

* Navigate to https://github.com/your_username
	+ Click **Repositories** tab
	+ Click **New**
	+ Enter workdir as the Repository name, click **Create repository**
* You now have an empty remote repository and some instructions to populate it

## Push an existing repository from your local computer
Go back to the loacl directory, workdir that we made in previous sections. 

> cd ~/Desktop/workdir

Add the github repo you just made as a remote repository that you want to push your data to

> git remote add origin https://github.com/your_username/workdir.git

Push your local repository to your Github

> git push –u origin master

## BONUS - SSH keys {-}
Here is a link to help you setup using SSH keys for authentication with Github
https://help.github.com/en/enterprise/2.15/user/articles/adding-a-new-ssh-key-to-your-github-account
