# Collaborating (`git fetch & pull`)

**Key terms/commands:**

* **git fetch**: look at the changes that is in your remote repository Github. This commands download the changes into the `.git/` folder so you can compare changes to your local files, but it does not actually modify your files (i.e., files outside of the `.git/` folder). 

* **git pull**: implement the changes you have *fetched* into your local files. 


## Setup a fake collaborator, yourself in another directory :) 

Clone the **workdir** repo into your local computer but a different folder as if you have a collaborator

> git clone https://github.com/your_username/workdir.git ~/Desktop/workdir_fake_collab
	
Lets pretend you are the collaborator, and you will make some changes and push it to Github

> cd ~/Desktop/workdir_fake_collab

> touch foofoo.txt

> git add foofoo.txt

> git commit -m "Add foofoo.txt"

> git push origin master


Lets check what is in the current folder 

> ls

Check what is on the workdir repository on Github. It should contain `foofoo.txt`

But what about the original `workdir` folder? 

> ls ~/Desktop/workdir

`foofoo.txt` should be missing. Now lets say you want to check what changes your collaborator made. 

## Implement the changes your fake collaborator made
**fetch** the changes your fake collaborator pushed to Github onto your local computer. 

> git fetch

NOTE that this does not change the files in your directory. But now you can use `git diff` to see what your collaborator has changed

> git diff master origin/master

If you decided these are changes you want in your local directory (the origainl `workdir`)

> git pull

## Notes {-}
* `git pull` returns message "Already up to date."
	+ `git pull` impelment the changes that were fetched by `git fetch`, so fetch first. 
* Will `git fetch` change my stuff? 
	+ Fetching does not change your local file until your pull. 

## BONUS - What is my remote? {-}
What is your remote? 

> git remote -v

Adding a different remote

> git add remote [name] [url]

Changing the URL of the remote (e.g., you change the remote repository)

> git remote set-url [name] [newurl]


## Really collaborating on Github

* Adding collaborators in your Github repository
	+ Click **Settings**
	+ Click **Collaborators** and add them (they need to be on Github)
	
* More Advance way to collaborate (won't cover in detail)
	+ **fork** a repository you want to make changes 
	+ **git clone** it to your local computer
	+ Make changes, **git add**, **git commit** and **git push** it to your forked remote repo
	+ Make a [Pull Request](https://help.github.com/en/articles/creating-a-pull-request) in the original repository